allOf:
  - $ref: '#/components/schemas/SiteKey'
  - type: object
    required:
      - attributes
    properties:
      attributes:
        type: object
        required:
          - name
        properties:
          name:
            type: string
            description: Site name
            example: Tumblr