name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  publish_docker_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build JAR
      uses: gradle/gradle-build-action@v2
      with:
        arguments: shadowJar
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wfeed-updater:${{ github.sha }}
